In [ ]:
# https://www.youtube.com/watch?v=J_LnPL3Qg70&list=PLeo1K3hjS3uvCeTYTeyfe0-rN5r8zn9rw&index=3

In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [31]:
df = pd.read_csv("homeprices3.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [32]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [33]:
# bedrooms.fillna()
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [34]:
model = linear_model.LinearRegression()
model.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [35]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [36]:
model.intercept_

221323.00186540408

In [37]:
model.predict([[3000, 3, 40]])

array([498408.25158031])

In [38]:
# y = mx + b, where
# m = [112.06244194, 23388.88007794, -3231.71790863]
# x = [3000, 3, 40]
# b = 221323.00186540408
# y = 112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540408
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540408

498408.2515740241

In [39]:
model.predict([[2500, 4, 5]])

array([578876.03748933])

## Exercise
In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**

## Answer
53713.86 and 93747.79

In [41]:
# problem: column 'experience' is of type object, which can't be converted to string for use by w2n.word_to_num()
# so to get past this, i modified file hiring.csv and fill in "zero" for those empty cells in column 'experience'

In [55]:
df2 = pd.read_csv("hiring3.csv")
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [56]:
# in column 'test_score(out of 10)', replace NaN with its median
median_interview = math.floor(df2['test_score(out of 10)'].median())
df2['test_score(out of 10)'] = df2['test_score(out of 10)'].fillna(median_interview)
df2['test_score(out of 10)']

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     8.0
7     7.0
Name: test_score(out of 10), dtype: float64

In [54]:
# df2.experience.fillna('zero')
# df2.experience

0       NaN
1       NaN
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [57]:
from word2number import w2n
df2.experience = df2.experience.apply(w2n.word_to_num)
df2.experience

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64

In [58]:
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [59]:
model = linear_model.LinearRegression()
model.fit(df2[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df2['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [61]:
print('coefficient:', model.coef_)
print('intercept:', model.intercept_)

coefficient: [2812.95487627 1845.70596798 2205.24017467]
intercept: 17737.26346433771


In [62]:
model.predict([[2, 9, 6]])

array([53205.96797671])

In [63]:
model.predict([[12, 10, 10]])

array([92002.18340611])