In [1]:
# https://www.youtube.com/watch?v=kft1AJ9WVDk
# TRAINING PROCESS
# 1. take the input from the training example and put them thru our formula to get the neuron's output
# 2. calculate the error, which is the difference between the output we got and the actual output
# 3. depending on the severity of the error, adjust the weights accordingly
# 4. repeat this 20,000 times

In [14]:
import numpy as np

In [27]:
training_input = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_output = np.array([[0, 1, 1, 0]]).T

np.random.seed(1)
weights = 2*np.random.random((3, 1)) - 1
print('Random starting synaptic weights')
print(weights)

Random starting synaptic weights
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [28]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def derivative(x):
    return x * (1 - x)

In [29]:
for i in range(100000):
    # Normalize the input layer with the synaptic weights
    input_layer = training_input
    output = sigmoid(np.dot(input_layer, weights))
    # how much did we miss?
    error = training_output - output
    # multiply error by the slope of the sigmoid
    adjustments = error * derivative(output)
    # update weights
    weights += np.dot(input_layer.T, adjustments)

print('Synaptic weights after training')
print(weights)
print('Output after training')
print(output)

Synaptic weights after training
[[12.00870061]
 [-0.2044116 ]
 [-5.8002822 ]]
Output after training
[[0.00301758]
 [0.99753723]
 [0.99799161]
 [0.00246109]]


In [30]:
class NeuralNetwork():
    def __init__(self):
        np.random.seed(1)
        self.synaptic_weights = 2*np.random.random((3, 1)) - 1
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)
    
    def train(self, training_input, training_output, n_iterations):
        for i in range(n_iterations):
            output = self.think(training_input)
            error = training_output - output
            adjustments = np.dot(training_input.T, error*self.sigmoid_derivative(output))
            self.synaptic_weights += adjustments
            
    def think(self, inputs):
        inputs = inputs.astype(float)
        output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
        return output

In [32]:
if __name__ == "__main__":
    neural_network = NeuralNetwork()

    print("Random starting synaptic weights: ")
    print(neural_network.synaptic_weights)

    training_inputs = np.array([[0,0,1],
                                [1,1,1],
                                [1,0,1],
                                [0,1,1]])
    training_outputs = np.array([[0,1,1,0]]).T

    # Train the neural network
    neural_network.train(training_inputs, training_outputs, 10000)

    print("Synaptic weights after training: ")
    print(neural_network.synaptic_weights)

    A = str(input("Input 1: "))
    B = str(input("Input 2: "))
    C = str(input("Input 3: "))
    
    print("New situation: input data = ", A, B, C)
    print("Output data: ")
    print(neural_network.think(np.array([A, B, C])))
    
    # some sample data
    # A=0, B=0, C=1; output=0.009664
    # A=1, B=0, C=0; output=0.99993704

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic weights after training: 
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
Input 1: 1
Input 2: 0
Input 3: 0
New situation: input data =  1 0 0
Output data: 
[0.99993704]
